// Copyright 2017-2021 @dust-defi/extension-base authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@dust-defi/extension-base', version: '0.41.2-a' };
